source :rubygems

gem 'serve'
gem 'haml', '~> 3.2.0.rc.1'
gem 'sass', '~> 3.2.0.alpha.247'
gem 'compass'
gem 'zurb-foundation'

# Use edge instead:
# gem 'serve', :git => 'git://github.com/jlong/serve.git'

# Markdown and Textile
# gem 'rdiscount' # Markdown
# gem 'RedCloth'  # Textile

# Other templating languages
# gem 'erubis'
# gem 'haml'
# gem 'slim'
# gem 'radius'
# gem 'less'

# Coffee Script
# gem 'coffee-script'

# Use mongrel for the Web server
# gem 'mongrel'
